-- ============================================================
-- Reference Data: Florida County FIPS codes and DOR Use Codes
-- Idempotent: safe to re-run (DROP IF EXISTS + CREATE)
-- ============================================================

-- ── ref_county: 67 Florida counties by FIPS code ────────────
DROP TABLE IF EXISTS ref_county;
CREATE TABLE ref_county (
    co_no   INTEGER PRIMARY KEY,
    county_name VARCHAR NOT NULL
);

INSERT INTO ref_county (co_no, county_name) VALUES
(1,  'Alachua'),
(2,  'Baker'),
(3,  'Bay'),
(4,  'Bradford'),
(5,  'Brevard'),
(6,  'Broward'),
(7,  'Calhoun'),
(8,  'Charlotte'),
(9,  'Citrus'),
(10, 'Clay'),
(11, 'Collier'),
(12, 'Columbia'),
(13, 'DeSoto'),
(14, 'Dixie'),
(15, 'Duval'),
(16, 'Escambia'),
(17, 'Flagler'),
(18, 'Franklin'),
(19, 'Gadsden'),
(20, 'Gilchrist'),
(21, 'Glades'),
(22, 'Gulf'),
(23, 'Hamilton'),
(24, 'Hardee'),
(25, 'Hendry'),
(26, 'Hernando'),
(27, 'Highlands'),
(28, 'Hillsborough'),
(29, 'Holmes'),
(30, 'Indian River'),
(31, 'Jackson'),
(32, 'Jefferson'),
(33, 'Lafayette'),
(34, 'Lake'),
(35, 'Lee'),
(36, 'Leon'),
(37, 'Levy'),
(38, 'Liberty'),
(39, 'Madison'),
(40, 'Manatee'),
(41, 'Marion'),
(42, 'Martin'),
(43, 'Miami-Dade'),
(44, 'Monroe'),
(45, 'Nassau'),
(46, 'Okaloosa'),
(47, 'Okeechobee'),
(48, 'Orange'),
(49, 'Osceola'),
(50, 'Palm Beach'),
(51, 'Pasco'),
(52, 'Pinellas'),
(53, 'Polk'),
(54, 'Putnam'),
(55, 'Santa Rosa'),
(56, 'Sarasota'),
(57, 'Seminole'),
(58, 'St. Johns'),
(59, 'St. Lucie'),
(60, 'Sumter'),
(61, 'Suwannee'),
(62, 'Taylor'),
(63, 'Union'),
(64, 'Volusia'),
(65, 'Wakulla'),
(66, 'Walton'),
(67, 'Washington'),
-- Special DOR codes (not standard FIPS counties)
(0,  'Statewide/Unknown'),
(68, 'DOR Centrally Assessed 1'),
(69, 'DOR Centrally Assessed 2'),
(70, 'DOR Centrally Assessed 3'),
(71, 'DOR Centrally Assessed 4'),
(72, 'DOR Centrally Assessed 5'),
(73, 'DOR Centrally Assessed 6'),
(74, 'DOR Centrally Assessed 7'),
(75, 'DOR Centrally Assessed 8'),
(76, 'DOR Centrally Assessed 9'),
(77, 'DOR Centrally Assessed 10');


-- ── ref_land_use: Florida DOR Use Codes ─────────────────────
-- Source: Florida Department of Revenue Property Tax Oversight
-- https://floridarevenue.com/property/Pages/DataPortal.aspx
DROP TABLE IF EXISTS ref_land_use;
CREATE TABLE ref_land_use (
    dor_uc      VARCHAR PRIMARY KEY,
    description VARCHAR NOT NULL,
    category    VARCHAR NOT NULL
);

INSERT INTO ref_land_use (dor_uc, description, category) VALUES
-- Residential (00-09)
('0000', 'Vacant Residential', 'Residential'),
('0001', 'Single Family Residential', 'Residential'),
('0002', 'Mobile Home', 'Residential'),
('0004', 'Condominium', 'Residential'),
('0005', 'Cooperatives', 'Residential'),
('0006', 'Retirement Homes (not eligible for exemption)', 'Residential'),
('0007', 'Miscellaneous Residential (boarding homes, etc.)', 'Residential'),
('0008', 'Multi-Family (less than 10 units)', 'Residential'),
('0009', 'Multi-Family (10 units or more)', 'Residential'),
-- Commercial (10-39)
('0010', 'Vacant Commercial', 'Commercial'),
('0011', 'Stores, One Story', 'Commercial'),
('0012', 'Mixed Use (store and office or store and residential)', 'Commercial'),
('0013', 'Department Store', 'Commercial'),
('0014', 'Supermarket', 'Commercial'),
('0015', 'Regional Shopping Center', 'Commercial'),
('0016', 'Community Shopping Center', 'Commercial'),
('0017', 'Office Building, One Story', 'Commercial'),
('0018', 'Office Building, Multi-Story', 'Commercial'),
('0019', 'Professional Service Building', 'Commercial'),
('0020', 'Airport, Bus Terminal, Marine Terminal', 'Commercial'),
('0021', 'Restaurant, Cafeteria', 'Commercial'),
('0022', 'Drive-In Restaurant', 'Commercial'),
('0023', 'Financial Institution', 'Commercial'),
('0024', 'Insurance Company Office', 'Commercial'),
('0025', 'Repair Service Shop', 'Commercial'),
('0026', 'Service Station', 'Commercial'),
('0027', 'Auto Sales, Repair, Storage', 'Commercial'),
('0028', 'Parking Lot, Mobile Home Sales, Used Car Sales', 'Commercial'),
('0029', 'Wholesale Outlet, Produce House', 'Commercial'),
('0030', 'Florist, Greenhouse', 'Commercial'),
('0031', 'Drive-In Theater, Open Stadium', 'Commercial'),
('0032', 'Enclosed Theater, Auditorium', 'Commercial'),
('0033', 'Night Club, Bar, Lounge', 'Commercial'),
('0034', 'Bowling Alley, Skating Rink, Pool Hall', 'Commercial'),
('0035', 'Tourist Attraction, Permanent Exhibit', 'Commercial'),
('0036', 'Camp, Lodge', 'Commercial'),
('0037', 'Race Horse, Auto, Dog Track', 'Commercial'),
('0038', 'Golf Course, Driving Range', 'Commercial'),
('0039', 'Hotel, Motel', 'Commercial'),
-- Industrial (40-49)
('0040', 'Vacant Industrial', 'Industrial'),
('0041', 'Light Manufacturing', 'Industrial'),
('0042', 'Heavy Manufacturing', 'Industrial'),
('0043', 'Lumber Yard, Sawmill, Planing Mill', 'Industrial'),
('0044', 'Packing Plant, Fruit/Vegetable Processing', 'Industrial'),
('0045', 'Bottling Plant, Cannery, Distillery', 'Industrial'),
('0046', 'Food Processing, Bakery', 'Industrial'),
('0047', 'Mineral Processing, Storage, Sales', 'Industrial'),
('0048', 'Warehouse, Distribution Terminal', 'Industrial'),
('0049', 'Open Storage, Supply Yard', 'Industrial'),
-- Agricultural (50-69)
('0050', 'Improved Agricultural', 'Agricultural'),
('0051', 'Cropland Soil Class 1', 'Agricultural'),
('0052', 'Cropland Soil Class 2', 'Agricultural'),
('0053', 'Cropland Soil Class 3', 'Agricultural'),
('0054', 'Timberland (site index 80+)', 'Agricultural'),
('0055', 'Timberland (site index 65-79)', 'Agricultural'),
('0056', 'Timberland (site index 55-64)', 'Agricultural'),
('0057', 'Timberland (site index <55)', 'Agricultural'),
('0058', 'Timberland (not classified by site index)', 'Agricultural'),
('0059', 'Timberland (not classified)', 'Agricultural'),
('0060', 'Grazing Land Soil Class 1', 'Agricultural'),
('0061', 'Grazing Land Soil Class 2', 'Agricultural'),
('0062', 'Grazing Land Soil Class 3', 'Agricultural'),
('0063', 'Grazing Land Soil Class 4', 'Agricultural'),
('0064', 'Grazing Land Soil Class 5', 'Agricultural'),
('0065', 'Grazing Land Soil Class 6', 'Agricultural'),
('0066', 'Ornamental, Miscellaneous Ag', 'Agricultural'),
('0067', 'Poultry, Bees, Tropical Fish, Rabbits', 'Agricultural'),
('0068', 'Dairies, Feed Lots', 'Agricultural'),
('0069', 'Ornamental, Miscellaneous Ag', 'Agricultural'),
-- Institutional (70-79)
('0070', 'Vacant Institutional', 'Institutional'),
('0071', 'Churches', 'Institutional'),
('0072', 'Private Schools, Colleges', 'Institutional'),
('0073', 'Private Hospital', 'Institutional'),
('0074', 'Homes for Aged', 'Institutional'),
('0075', 'Orphanages, Non-Profit Service', 'Institutional'),
('0076', 'Mortuaries, Cemeteries', 'Institutional'),
('0077', 'Clubs, Lodges, Union Halls', 'Institutional'),
('0078', 'Sanitariums, Convalescent, Rest Homes', 'Institutional'),
('0079', 'Cultural Organizations, Facilities', 'Institutional'),
-- Government (80-89)
('0080', 'Vacant Government', 'Government'),
('0081', 'Military', 'Government'),
('0082', 'Forest, Parks, Recreational', 'Government'),
('0083', 'Public County Schools', 'Government'),
('0084', 'Colleges', 'Government'),
('0085', 'Hospitals', 'Government'),
('0086', 'Counties (other than listed)', 'Government'),
('0087', 'State (other than listed)', 'Government'),
('0088', 'Federal (other than listed)', 'Government'),
('0089', 'Municipal (other than listed)', 'Government'),
-- Miscellaneous (90-99)
('0090', 'Leasehold Interest (government-owned property)', 'Miscellaneous'),
('0091', 'Utility, Gas & Electric', 'Miscellaneous'),
('0092', 'Mining, Petroleum, Gas Lands', 'Miscellaneous'),
('0093', 'Subsurface Rights', 'Miscellaneous'),
('0094', 'Right-of-Way, Streets, Roads', 'Miscellaneous'),
('0095', 'Rivers, Lakes, Submerged Lands', 'Miscellaneous'),
('0096', 'Sewage Disposal, Waste Lands', 'Miscellaneous'),
('0097', 'Outdoor Recreational or Park Land (classified)', 'Miscellaneous'),
('0098', 'Centrally Assessed', 'Miscellaneous'),
('0099', 'Non-Agricultural Acreage', 'Miscellaneous'),
('0003', 'Multi-Family (3 units)', 'Residential'),
('    ', 'Unknown/Blank', 'Miscellaneous');
